apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: backend-ingress
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:
      - backend:
          service:
            name: finanse-backend
            port:
              number: 5000
        path: /api
        pathType: Prefix
status:
  loadBalancer: {}
